.\" This is a comment
.\" Contact johnk@riceball.com
.TH man 1 "10 October 2012" ".1" "eazycz"
.SH NAME
easycz \- script launcher
.SH SYNOPSIS
Easy CZ (clonezilla) script launcher.
.SH DESCRIPTION
This is a simple graphical user interface program
that admins can use to create push-button
interfaces, also known as "switchboards",
for novice users. The configuration is
done with a YAML file. There is no way for the intended end
user to alter the interface through this program.
This is considered a feature, not a bug.
.PP
The configuration file format is YAML.
.PP
It was originally intended to launch Clonezilla commands, thus
the name.
.SH OPTIONS
.TP
\-c <configfile>
specify a config file
.TP
\-d
debug
.TP
\-f 
forces full-screen mode
.SH CONFIG FILES
EasyCZ searches for the config file in three locations.
First, if the user specifies a file, it tries that.
Second, it looks for a file named conf.yaml in the current
directory.  Third, it looks in ~/.easycz/.
If it finds it, it will chdir to that directory
and relative references to images files or other files will be relative
to the conf.yaml file's directory.
.PP
You can develop your swithcboard by working within a
directory.  When it's done, you can invoke that switchboard by using
the -c option and specifying the conf.yaml file within that directory.
For simplicity, you may want to create a hierarchy of directories
within ~/.easycz.
.PP
The structure of the config file is YAML.  The syntax is as follows:
 title: "string that is the window's title"
 table:
   - title: "a row in the table that acts as a title"
   - icons:
     - title:
       icon:
       command:
     - title:
       icon:
       command:
   - icons:
     - title:
       command:

A table contains a sequence of either icons or titles.  "icons" is a
collection of buttons, and each has a title, command, and an optional
"icon".  An "icon" can be a JPEG, PNG, or any other format supported by GTK+.

.SH FILES
~/.easycz/ default location for config files and directories.
conf.yaml default name for the config file in the current directory.
.SH SEE ALSO
clonezilla(1)
.SH BUGS
Malformed YAML files don't work at all, but error messages aren't
helpful.
.PP
Icons and other resources are stored relative to the current directory
if the config file name is specified.
.SH AUTHOR
John K <johnk@riceball.com>
